swagger: "2.0"
info:
  version: "1.0.0"
  title: "super-riddikulus-server"
host: localhost:3008
basePath: /
paths: 
  /note:
    get: 
      summary: Gets all user notes
      responses:
        200:
          description: OK
    post:
      summary: Adds a new note
      requestBody: 
        content: 
          application/json:
            schema: 
              $ref: '#/components/schemas/Note'
      responses:
        201:
          description: Created
  /note/:id:
    get: 
      summary: 
      description: 
      responses:
        200:
          description: OK
    patch:
      summary: 
      description: 
      responses:
        200:
          description: OK
    delete:
      summary: 
      description: 
      responses:
        200:
          description: OK
    
    
    